version: "3"

services:
  bot:
    image: "node"
    build:
      context: .
      dockerfile: Dockerfile
    restart: always
    environment:
      - NODE_ENV=production
      - REDIS_HOST=10.0.11.3
      - REDIS_PASSWORD=remoteremote
    depends_on:
      - "redis"
    networks:
      backend:
        ipv4_address: 10.0.11.4

  redis:
    restart: always
    image: "redis"
    volumes:
      - ./redis.conf:/usr/local/etc/redis/redis.conf
    command: ["redis-server", "/usr/local/etc/redis/redis.conf"]
    ports:
      - "6380:6379"
    networks:
      backend:
        ipv4_address: 10.0.11.3

networks:
  backend:
    ipam:
      driver: default
      config:
        - subnet: "10.0.11.0/24"
